import type { LevelDef, WaveRewardDef } from './types';
import type { NormalZombieId } from './zombies';

export interface LevelTemplate extends Omit<LevelDef, 'waves' | 'boss'> {
  stages: { mix: { type: NormalZombieId; weight: number }[]; rewards: WaveRewardDef[] }[];
}

export const LEVEL_TEMPLATES: LevelTemplate[] = [
  {
    id: 'level_1',
    name: '第一关:郊外',
    briefing: '清理外缘感染体，守住撤离通道。\n利用油桶开路，用粉尘区截断追击。',
    props: [
      { type: 'barrel_oil', x: 400, y: 300 },
      { type: 'barrel_flour', x: 900, y: 500 },
      { type: 'barrel_oil', x: 700, y: 200 },
    ],
    obstacles: [
      { kind: 'container', x: 320, y: 520, width: 150, height: 60 },
      { kind: 'container', x: 980, y: 240, width: 60, height: 150 },
      { kind: 'container', x: 640, y: 150, width: 130, height: 54, rotation: 8 },
    ],
    stages: [{ mix: [{ type: 'walker', weight: 5 }, { type: 'drifter', weight: 3 }], rewards: [{ type: 'weapon', weaponId: 'smg', ammo: 40 }] },
      { mix: [{ type: 'walker', weight: 6 }, { type: 'runner', weight: 3 }, { type: 'lurker', weight: 2 }, { type: 'rotting', weight: 2 }], rewards: [{ type: 'weapon', weaponId: 'shotgun', ammo: 18 }, { type: 'medicine', medicineId: 'bandage', amount: 1 }, { type: 'enhancement' }] },
      { mix: [{ type: 'walker', weight: 7 }, { type: 'runner', weight: 4 }, { type: 'lurker', weight: 2 }, { type: 'rotting', weight: 3 }, { type: 'tank', weight: 1 }], rewards: [] }],
  },
  {
    id: 'level_2',
    name: '第二关:废车站',
    briefing: '靠近广播站启动诱敌，把基础尸群引向油桶。\n重装与远程不受广播影响，留意巨型坦克。',
    lures: [
      { id: 'station-west-broadcast', x: 350, y: 300 },
      { id: 'station-east-broadcast', x: 930, y: 420 },
    ],
    props: [
      { type: 'barrel_oil', x: 270, y: 360 },
      { type: 'barrel_oil', x: 270, y: 450 },
      { type: 'barrel_oil', x: 1010, y: 360 },
      { type: 'barrel_oil', x: 1010, y: 450 },
      { type: 'barrel_flour', x: 470, y: 520 },
      { type: 'barrel_flour', x: 810, y: 200 },
    ],
    obstacles: [
      { kind: 'wreck', x: 270, y: 205, width: 150, height: 72, rotation: -8 },
      { kind: 'wreck', x: 1010, y: 205, width: 150, height: 72, rotation: 8 },
      { kind: 'container', x: 360, y: 520, width: 180, height: 58 },
      { kind: 'container', x: 920, y: 520, width: 180, height: 58 },
      { kind: 'barricade', x: 640, y: 145, width: 150, height: 40 },
    ],
    stages: [{ mix: [{ type: 'walker', weight: 46 }, { type: 'runner', weight: 14 }, { type: 'lurker', weight: 3 }], rewards: [{ type: 'weapon', weaponId: 'smg', ammo: 80 }, { type: 'enhancement' }] },
      { mix: [{ type: 'walker', weight: 122 }, { type: 'runner', weight: 28 }, { type: 'lurker', weight: 10 }, { type: 'tank', weight: 3 }], rewards: [{ type: 'weapon', weaponId: 'shotgun', ammo: 18 }] },
      { mix: [{ type: 'walker', weight: 89 }, { type: 'runner', weight: 22 }, { type: 'lurker', weight: 18 }, { type: 'tank', weight: 8 }], rewards: [{ type: 'weapon', weaponId: 'rifle', ammo: 60 }, { type: 'enhancement' }] }],
  },
  {
    id: 'level_3',
    name: '第三关:封锁城区',
    briefing: '把感染体引到标记危墙旁，打塌墙体压倒敌群。\n利用新缺口换位，反制爆破者轰炸。',
    props: [
      { type: 'barrel_oil', x: 240, y: 420 },
      { type: 'barrel_flour', x: 430, y: 210 },
      { type: 'barrel_oil', x: 690, y: 280 },
      { type: 'barrel_flour', x: 920, y: 470 },
      { type: 'barrel_oil', x: 1080, y: 220 },
    ],
    obstacles: [
      {
        kind: 'barricade', x: 360, y: 300, width: 118, height: 40, rotation: 90,
        breakable: {
          id: 'level3-west-wall', health: 260, crackedHealthRatio: 0.55,
          collapseDamage: 220, collapseRadius: 126, bossDamageFactor: 0.25,
        },
      },
      {
        kind: 'barricade', x: 920, y: 300, width: 118, height: 40, rotation: 90,
        breakable: {
          id: 'level3-east-wall', health: 260, crackedHealthRatio: 0.55,
          collapseDamage: 220, collapseRadius: 126, bossDamageFactor: 0.25,
        },
      },
      { kind: 'barricade', x: 500, y: 560, width: 150, height: 40 },
      { kind: 'barricade', x: 800, y: 560, width: 150, height: 40 },
      { kind: 'container', x: 200, y: 180, width: 150, height: 56, rotation: 12 },
      { kind: 'container', x: 1090, y: 560, width: 160, height: 56, rotation: -10 },
      { kind: 'wreck', x: 640, y: 150, width: 150, height: 70 },
    ],
    stages: [{ mix: [{ type: 'walker', weight: 20 }, { type: 'runner', weight: 8 }, { type: 'bomber', weight: 5 }, { type: 'lurker', weight: 2 }], rewards: [{ type: 'weapon', weaponId: 'ak47', ammo: 90 }] },
      { mix: [{ type: 'walker', weight: 20 }, { type: 'runner', weight: 8 }, { type: 'bomber', weight: 8 }, { type: 'crawler', weight: 4 }, { type: 'lurker', weight: 2 }], rewards: [{ type: 'weapon', weaponId: 'm79', ammo: 12 }] },
      { mix: [{ type: 'walker', weight: 20 }, { type: 'runner', weight: 8 }, { type: 'bomber', weight: 8 }, { type: 'crawler', weight: 5 }, { type: 'lurker', weight: 2 }], rewards: [] }],
  },
  {
    id: 'level_4',
    name: '第四关:排水渠',
    briefing: '守住四条狭窄水道，优先清除高速目标。\n不要被中央障碍切断退路。',
    props: [
      { type: 'barrel_oil', x: 200, y: 360 },
      { type: 'barrel_flour', x: 640, y: 180 },
      { type: 'barrel_oil', x: 640, y: 540 },
      { type: 'barrel_flour', x: 1080, y: 360 },
    ],
    obstacles: [
      { kind: 'barricade', x: 320, y: 240, width: 200, height: 38 },
      { kind: 'barricade', x: 320, y: 480, width: 200, height: 38 },
      { kind: 'barricade', x: 960, y: 240, width: 200, height: 38 },
      { kind: 'barricade', x: 960, y: 480, width: 200, height: 38 },
      { kind: 'container', x: 540, y: 360, width: 150, height: 56, rotation: 90 },
    ],
    stages: [{ mix: [{ type: 'walker', weight: 5 }, { type: 'crawler', weight: 6 }, { type: 'feral', weight: 4 }, { type: 'drifter', weight: 3 }], rewards: [{ type: 'weapon', weaponId: 'dual_uzi', ammo: 128 }] },
      { mix: [{ type: 'crawler', weight: 6 }, { type: 'feral', weight: 5 }, { type: 'rotting', weight: 4 }, { type: 'drifter', weight: 4 }, { type: 'bloodied', weight: 2 }], rewards: [{ type: 'medicine', medicineId: 'medkit', amount: 1 }] },
      { mix: [{ type: 'crawler', weight: 5 }, { type: 'feral', weight: 5 }, { type: 'rotting', weight: 3 }, { type: 'lurker', weight: 3 }, { type: 'stalker', weight: 3 }, { type: 'tank', weight: 1 }], rewards: [] },
      { mix: [{ type: 'feral', weight: 6 }, { type: 'crawler', weight: 5 }, { type: 'stalker', weight: 3 }, { type: 'bloodied', weight: 3 }, { type: 'tank', weight: 2 }, { type: 'headless', weight: 2 }], rewards: [{ type: 'weapon', weaponId: 'aa12', ammo: 40 }] }],
  },
  {
    id: 'level_5',
    name: '第五关:检疫所',
    briefing: '利用四角掩体诱导猎杀者冲锋落空。\n其贴身震荡前及时拉开距离。',
    props: [
      { type: 'barrel_oil', x: 260, y: 360 },
      { type: 'barrel_flour', x: 470, y: 210 },
      { type: 'barrel_oil', x: 810, y: 510 },
      { type: 'barrel_flour', x: 1020, y: 360 },
      { type: 'barrel_oil', x: 640, y: 610 },
    ],
    obstacles: [
      { kind: 'container', x: 250, y: 190, width: 160, height: 58 },
      { kind: 'container', x: 1030, y: 190, width: 160, height: 58 },
      { kind: 'container', x: 250, y: 530, width: 160, height: 58 },
      { kind: 'container', x: 1030, y: 530, width: 160, height: 58 },
      { kind: 'barricade', x: 640, y: 170, width: 150, height: 40 },
      { kind: 'wreck', x: 640, y: 480, width: 148, height: 72, rotation: -12 },
    ],
    stages: [{ mix: [{ type: 'walker', weight: 4 }, { type: 'stalker', weight: 3 }, { type: 'drifter', weight: 4 }], rewards: [{ type: 'weapon', weaponId: 'm16a4', ammo: 60 }] },
      { mix: [{ type: 'stalker', weight: 6 }, { type: 'oddity', weight: 2 }, { type: 'bloodied', weight: 3 }, { type: 'runner', weight: 4 }], rewards: [] },
      { mix: [{ type: 'stalker', weight: 3 }, { type: 'oddity', weight: 3 }, { type: 'headless', weight: 3 }, { type: 'tank', weight: 2 }], rewards: [{ type: 'weapon', weaponId: 'barrett', ammo: 16 }] },
      { mix: [{ type: 'feral', weight: 4 }, { type: 'stalker', weight: 6 }, { type: 'oddity', weight: 4 }, { type: 'bloodied', weight: 3 }, { type: 'tank', weight: 1 }], rewards: [] }],
  },
  {
    id: 'level_6',
    name: '第六关:货运场',
    briefing: '在成排集装箱间保持横向机动。\n集中火力处理重装感染体。',
    props: [
      { type: 'barrel_oil', x: 300, y: 200 },
      { type: 'barrel_oil', x: 980, y: 200 },
      { type: 'barrel_flour', x: 420, y: 540 },
      { type: 'barrel_flour', x: 860, y: 540 },
      { type: 'barrel_oil', x: 640, y: 490 },
    ],
    obstacles: [
      { kind: 'container', x: 260, y: 330, width: 180, height: 60, rotation: 90 },
      { kind: 'container', x: 1020, y: 330, width: 180, height: 60, rotation: 90 },
      { kind: 'container', x: 640, y: 160, width: 210, height: 58 },
      { kind: 'container', x: 640, y: 570, width: 210, height: 58 },
      { kind: 'wreck', x: 450, y: 380, width: 150, height: 72, rotation: 22 },
      { kind: 'wreck', x: 840, y: 380, width: 150, height: 72, rotation: -22 },
    ],
    stages: [{ mix: [{ type: 'walker', weight: 5 }, { type: 'headless', weight: 2 }, { type: 'bloodied', weight: 3 }, { type: 'drifter', weight: 3 }], rewards: [{ type: 'weapon', weaponId: 'gatling', ammo: 360 }] },
      { mix: [{ type: 'bloodied', weight: 4 }, { type: 'headless', weight: 3 }, { type: 'rotting', weight: 4 }, { type: 'runner', weight: 5 }], rewards: [] },
      { mix: [{ type: 'headless', weight: 3 }, { type: 'bloater', weight: 2 }, { type: 'tank', weight: 2 }, { type: 'bomber', weight: 3 }, { type: 'crawler', weight: 4 }], rewards: [{ type: 'weapon', weaponId: 'golden_m249', ammo: 200 }] },
      { mix: [{ type: 'bloodied', weight: 4 }, { type: 'headless', weight: 4 }, { type: 'bloater', weight: 2 }, { type: 'tank', weight: 2 }, { type: 'bomber', weight: 3 }], rewards: [] }],
  },
  {
    id: 'level_7',
    name: '第七关:塌陷街区',
    briefing: '在碎片化通路间反复转换阵地。\n优先压制远程与爆炸目标。',
    props: [
      { type: 'barrel_oil', x: 230, y: 250 },
      { type: 'barrel_flour', x: 500, y: 460 },
      { type: 'barrel_oil', x: 700, y: 200 },
      { type: 'barrel_flour', x: 900, y: 480 },
      { type: 'barrel_oil', x: 1070, y: 280 },
      { type: 'barrel_oil', x: 640, y: 600 },
    ],
    obstacles: [
      { kind: 'wreck', x: 300, y: 400, width: 152, height: 74, rotation: 34 },
      { kind: 'wreck', x: 990, y: 400, width: 152, height: 74, rotation: -34 },
      { kind: 'wreck', x: 640, y: 280, width: 150, height: 72, rotation: 8 },
      { kind: 'barricade', x: 420, y: 170, width: 150, height: 40, rotation: 20 },
      { kind: 'barricade', x: 870, y: 170, width: 150, height: 40, rotation: -20 },
      { kind: 'barricade', x: 350, y: 590, width: 160, height: 40 },
      { kind: 'container', x: 950, y: 590, width: 170, height: 56, rotation: -8 },
    ],
    stages: [{ mix: [{ type: 'runner', weight: 5 }, { type: 'crawler', weight: 5 }, { type: 'lurker', weight: 3 }, { type: 'walker', weight: 4 }], rewards: [{ type: 'weapon', weaponId: 'tesla', ammo: 48 }] },
      { mix: [{ type: 'lurker', weight: 4 }, { type: 'oddity', weight: 3 }, { type: 'bloater', weight: 2 }, { type: 'feral', weight: 5 }], rewards: [] },
      { mix: [{ type: 'oddity', weight: 4 }, { type: 'bloater', weight: 3 }, { type: 'headless', weight: 3 }, { type: 'tank', weight: 2 }, { type: 'stalker', weight: 3 }], rewards: [{ type: 'weapon', weaponId: 'railgun', ammo: 20 }] },
      { mix: [{ type: 'bloater', weight: 3 }, { type: 'oddity', weight: 4 }, { type: 'bomber', weight: 4 }, { type: 'tank', weight: 2 }, { type: 'feral', weight: 4 }], rewards: [] }],
  },
  {
    id: 'level_8',
    name: '第八关:研究站',
    briefing: '利用规整掩体切断远程感染体视线。\n避免在中央开阔区停留。',
    props: [
      { type: 'barrel_flour', x: 250, y: 250 },
      { type: 'barrel_flour', x: 1030, y: 250 },
      { type: 'barrel_oil', x: 250, y: 470 },
      { type: 'barrel_oil', x: 1030, y: 470 },
      { type: 'barrel_flour', x: 640, y: 460 },
    ],
    obstacles: [
      { kind: 'container', x: 440, y: 220, width: 150, height: 56 },
      { kind: 'container', x: 840, y: 220, width: 150, height: 56 },
      { kind: 'container', x: 440, y: 500, width: 150, height: 56 },
      { kind: 'container', x: 840, y: 500, width: 150, height: 56 },
      { kind: 'barricade', x: 640, y: 150, width: 160, height: 40 },
      { kind: 'barricade', x: 640, y: 580, width: 160, height: 40 },
      { kind: 'wreck', x: 740, y: 360, width: 148, height: 70, rotation: 90 },
    ],
    stages: [{ mix: [{ type: 'drifter', weight: 5 }, { type: 'lurker', weight: 4 }, { type: 'rotting', weight: 4 }, { type: 'walker', weight: 4 }], rewards: [{ type: 'weapon', weaponId: 'cryo_sprayer', ammo: 140 }] },
      { mix: [{ type: 'oddity', weight: 4 }, { type: 'lurker', weight: 4 }, { type: 'rotting', weight: 4 }, { type: 'crawler', weight: 5 }], rewards: [] },
      { mix: [{ type: 'oddity', weight: 5 }, { type: 'rotting', weight: 4 }, { type: 'stalker', weight: 4 }, { type: 'headless', weight: 3 }, { type: 'tank', weight: 1 }], rewards: [{ type: 'medicine', medicineId: 'medkit', amount: 1 }] },
      { mix: [{ type: 'oddity', weight: 5 }, { type: 'lurker', weight: 4 }, { type: 'bloater', weight: 3 }, { type: 'feral', weight: 5 }, { type: 'tank', weight: 2 }], rewards: [] }],
  },
  {
    id: 'level_9',
    name: '第九关:焚化厂',
    briefing: '控制油桶连锁方向，避免封死自身退路。\n先清除靠近爆炸链的威胁。',
    props: [
      { type: 'barrel_oil', x: 220, y: 220 },
      { type: 'barrel_oil', x: 1060, y: 220 },
      { type: 'barrel_oil', x: 220, y: 500 },
      { type: 'barrel_oil', x: 1060, y: 500 },
      { type: 'barrel_oil', x: 640, y: 210 },
      { type: 'barrel_flour', x: 460, y: 380 },
      { type: 'barrel_flour', x: 820, y: 380 },
    ],
    obstacles: [
      { kind: 'container', x: 340, y: 330, width: 170, height: 58, rotation: 90 },
      { kind: 'container', x: 940, y: 330, width: 170, height: 58, rotation: 90 },
      { kind: 'wreck', x: 640, y: 470, width: 150, height: 72 },
      { kind: 'barricade', x: 470, y: 590, width: 160, height: 40 },
      { kind: 'barricade', x: 810, y: 590, width: 160, height: 40 },
      { kind: 'barricade', x: 640, y: 130, width: 170, height: 40 },
    ],
    stages: [{ mix: [{ type: 'bomber', weight: 5 }, { type: 'walker', weight: 5 }, { type: 'crawler', weight: 5 }, { type: 'runner', weight: 4 }], rewards: [] },
      { mix: [{ type: 'bomber', weight: 5 }, { type: 'bloater', weight: 3 }, { type: 'feral', weight: 5 }, { type: 'rotting', weight: 4 }], rewards: [{ type: 'weapon', weaponId: 'flamethrower', ammo: 180 }] },
      { mix: [{ type: 'bloater', weight: 4 }, { type: 'bomber', weight: 5 }, { type: 'oddity', weight: 4 }, { type: 'tank', weight: 2 }, { type: 'headless', weight: 3 }], rewards: [] },
      { mix: [{ type: 'bomber', weight: 6 }, { type: 'bloater', weight: 4 }, { type: 'tank', weight: 3 }, { type: 'oddity', weight: 4 }, { type: 'bloodied', weight: 4 }], rewards: [] }],
  },
  {
    id: 'level_10',
    name: '第十关:感染源核心',
    briefing: '借四组掩体推进至感染源核心。\n躲开孢群轰炸，终结腐化母体。',
    props: [
      { type: 'barrel_oil', x: 200, y: 200 },
      { type: 'barrel_oil', x: 1080, y: 200 },
      { type: 'barrel_flour', x: 200, y: 520 },
      { type: 'barrel_flour', x: 1080, y: 520 },
      { type: 'barrel_oil', x: 400, y: 360 },
      { type: 'barrel_oil', x: 880, y: 360 },
      { type: 'barrel_flour', x: 640, y: 620 },
    ],
    obstacles: [
      { kind: 'container', x: 380, y: 230, width: 130, height: 56, rotation: 45 },
      { kind: 'container', x: 900, y: 230, width: 130, height: 56, rotation: -45 },
      { kind: 'container', x: 380, y: 490, width: 130, height: 56, rotation: -45 },
      { kind: 'container', x: 900, y: 490, width: 130, height: 56, rotation: 45 },
      { kind: 'wreck', x: 640, y: 150, width: 150, height: 70 },
      { kind: 'wreck', x: 640, y: 570, width: 150, height: 70 },
      { kind: 'barricade', x: 150, y: 360, width: 150, height: 40, rotation: 90 },
      { kind: 'barricade', x: 1130, y: 360, width: 150, height: 40, rotation: 90 },
    ],
    stages: [{ mix: [{ type: 'walker', weight: 5 }, { type: 'runner', weight: 5 }, { type: 'drifter', weight: 5 }, { type: 'crawler', weight: 5 }], rewards: [] },
      { mix: [{ type: 'feral', weight: 5 }, { type: 'stalker', weight: 4 }, { type: 'lurker', weight: 4 }, { type: 'rotting', weight: 4 }, { type: 'bloodied', weight: 3 }], rewards: [] },
      { mix: [{ type: 'headless', weight: 4 }, { type: 'bloodied', weight: 4 }, { type: 'oddity', weight: 4 }, { type: 'bloater', weight: 3 }, { type: 'tank', weight: 2 }], rewards: [{ type: 'weapon', weaponId: 'rpg', ammo: 8 }] },
      { mix: [{ type: 'oddity', weight: 5 }, { type: 'bloater', weight: 4 }, { type: 'bomber', weight: 5 }, { type: 'tank', weight: 3 }, { type: 'stalker', weight: 4 }], rewards: [] },
      { mix: [{ type: 'feral', weight: 4 }, { type: 'crawler', weight: 4 }, { type: 'headless', weight: 4 }, { type: 'bloater', weight: 3 }, { type: 'oddity', weight: 4 }, { type: 'tank', weight: 3 }, { type: 'bomber', weight: 4 }], rewards: [] }],
  }
];
